### ISSUE TITLE
SearchViewController.swift cannot be found

### ISSUE THREAD

**Issue by JimboPower** [angelodig/Covid-19_Stats#1]
Ciao Angelo! Sono Edoardo coach iOS Development di Start2Impact. Purtroppo quando compilo il tuo codice mi viene fuori questo errore:

`error: Build input file cannot be found: '/Users/edoardodecal/Downloads/Covid-19_Stats-master/Covid-19_Stats/ViewController/Select Country VC/SearchViewController.swift' (in target 'Covid-19_Stats' from project 'Covid-19_Stats')`

Probabilmente nella tua repo Github ti sei dimenticato il file.

Un saluto,

Edoardo

**Comment by angelodig** [comment]
Ciao Edoardo, adesso dovrebbe andare
